version: '3.1'

services:
  mysql:
    image: mysql:5.7.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - './volumes/mysql:/var/lib/mysql'
      - './scripts:/docker-entrypoint-initdb.d/'