Order:
  type: object
  properties:
    order_id:
      type: number
      required: true
      description: 订单 ID
    amount:
      type: number
      required: true
      description: 商品数量
    product_id:
      type: number
      required: true
      description: 商品 ID
    total_price:
      type: number
      required: true
      description: 订单总价 ID
    name:
      type: string
      required: true
      description: 商品名称 ID
